import { mutation } from "./_generated/server";

const SEED_THEMES = [
  {
    name: "Midnight Purple",
    slug: "midnight-purple",
    description: "A deep, immersive dark theme with rich purple accents",
    colors: {
      background: "#0a0a1a",
      foreground: "#e4e4f0",
      primary: "#7c3aed",
      secondary: "#1e1b4b",
      accent: "#c084fc",
      muted: "#6b6b8a",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#c084fc",
      string: "#a3e635",
      comment: "#6b6b8a",
      function: "#7c3aed",
      variable: "#e4e4f0",
      type: "#fb923c",
      number: "#f472b6",
      operator: "#94a3b8",
      punctuation: "#6b6b8a",
    },
    discord: {
      backgroundPrimary: "#14142a",
      backgroundSecondary: "#0f0f24",
      backgroundTertiary: "#0a0a1a",
      backgroundFloating: "#060610",
      textNormal: "#e4e4f0",
      textMuted: "#6b6b8a",
      textLink: "#c084fc",
      interactiveNormal: "#a0a0c0",
      interactiveHover: "#e4e4f0",
      interactiveActive: "#ffffff",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#7c3aed",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#e4e4f0",
      accentForeground: "#0a0a1a",
      mutedForeground: "#e4e4f0",
      card: "#0f0f24",
      cardForeground: "#e4e4f0",
      popover: "#0f0f24",
      popoverForeground: "#e4e4f0",
      border: "#2a2760",
      input: "#2a2760",
      ring: "#7c3aed",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Ocean Breeze",
    slug: "ocean-breeze",
    description: "Cool, calming tones inspired by the sea",
    colors: {
      background: "#0c1222",
      foreground: "#e0f2fe",
      primary: "#0ea5e9",
      secondary: "#0c4a6e",
      accent: "#38bdf8",
      muted: "#64748b",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#38bdf8",
      string: "#4ade80",
      comment: "#64748b",
      function: "#0ea5e9",
      variable: "#e0f2fe",
      type: "#fbbf24",
      number: "#f472b6",
      operator: "#7dd3fc",
      punctuation: "#64748b",
    },
    discord: {
      backgroundPrimary: "#1a2535",
      backgroundSecondary: "#131e30",
      backgroundTertiary: "#0c1222",
      backgroundFloating: "#070e18",
      textNormal: "#e0f2fe",
      textMuted: "#64748b",
      textLink: "#38bdf8",
      interactiveNormal: "#93c5fd",
      interactiveHover: "#e0f2fe",
      interactiveActive: "#ffffff",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#0ea5e9",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#e0f2fe",
      accentForeground: "#0c1222",
      mutedForeground: "#e0f2fe",
      card: "#131e30",
      cardForeground: "#e0f2fe",
      popover: "#131e30",
      popoverForeground: "#e0f2fe",
      border: "#1e3a5f",
      input: "#1e3a5f",
      ring: "#0ea5e9",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Forest Canopy",
    slug: "forest-canopy",
    description: "Earthy greens and warm browns inspired by nature",
    colors: {
      background: "#0a1208",
      foreground: "#e8f5e2",
      primary: "#22c55e",
      secondary: "#14532d",
      accent: "#4ade80",
      muted: "#6b7c6a",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#4ade80",
      string: "#86efac",
      comment: "#6b7c6a",
      function: "#22c55e",
      variable: "#e8f5e2",
      type: "#fbbf24",
      number: "#f87171",
      operator: "#86efac",
      punctuation: "#6b7c6a",
    },
    discord: {
      backgroundPrimary: "#162010",
      backgroundSecondary: "#101a0d",
      backgroundTertiary: "#0a1208",
      backgroundFloating: "#060b05",
      textNormal: "#e8f5e2",
      textMuted: "#6b7c6a",
      textLink: "#4ade80",
      interactiveNormal: "#a7d9a0",
      interactiveHover: "#e8f5e2",
      interactiveActive: "#ffffff",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#22c55e",
    },
    tailwind: {
      primaryForeground: "#0a1208",
      secondaryForeground: "#e8f5e2",
      accentForeground: "#0a1208",
      mutedForeground: "#e8f5e2",
      card: "#101a0d",
      cardForeground: "#e8f5e2",
      popover: "#101a0d",
      popoverForeground: "#e8f5e2",
      border: "#1a3a1a",
      input: "#1a3a1a",
      ring: "#22c55e",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Sunset Glow",
    slug: "sunset-glow",
    description: "Warm oranges and soft pinks evoking a golden hour sky",
    colors: {
      background: "#1a0a0a",
      foreground: "#fef2e8",
      primary: "#f97316",
      secondary: "#7c2d12",
      accent: "#fb923c",
      muted: "#92716a",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#fb923c",
      string: "#fbbf24",
      comment: "#92716a",
      function: "#f97316",
      variable: "#fef2e8",
      type: "#f472b6",
      number: "#a78bfa",
      operator: "#fed7aa",
      punctuation: "#92716a",
    },
    discord: {
      backgroundPrimary: "#2e1a1a",
      backgroundSecondary: "#251212",
      backgroundTertiary: "#1a0a0a",
      backgroundFloating: "#0f0505",
      textNormal: "#fef2e8",
      textMuted: "#92716a",
      textLink: "#fb923c",
      interactiveNormal: "#fcd9b0",
      interactiveHover: "#fef2e8",
      interactiveActive: "#ffffff",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#f97316",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#fef2e8",
      accentForeground: "#1a0a0a",
      mutedForeground: "#fef2e8",
      card: "#251212",
      cardForeground: "#fef2e8",
      popover: "#251212",
      popoverForeground: "#fef2e8",
      border: "#4a2020",
      input: "#4a2020",
      ring: "#f97316",
      destructive: "#b91c1c",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Rose Gold",
    slug: "rose-gold",
    description: "Elegant pinks and golds for a luxurious feel",
    colors: {
      background: "#1a0f14",
      foreground: "#fce7f3",
      primary: "#ec4899",
      secondary: "#831843",
      accent: "#f472b6",
      muted: "#8b6b7a",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#f472b6",
      string: "#86efac",
      comment: "#8b6b7a",
      function: "#ec4899",
      variable: "#fce7f3",
      type: "#fbbf24",
      number: "#a78bfa",
      operator: "#fbcfe8",
      punctuation: "#8b6b7a",
    },
    discord: {
      backgroundPrimary: "#2d1c23",
      backgroundSecondary: "#241620",
      backgroundTertiary: "#1a0f14",
      backgroundFloating: "#10080d",
      textNormal: "#fce7f3",
      textMuted: "#8b6b7a",
      textLink: "#f472b6",
      interactiveNormal: "#f9a8d4",
      interactiveHover: "#fce7f3",
      interactiveActive: "#ffffff",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#ec4899",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#fce7f3",
      accentForeground: "#1a0f14",
      mutedForeground: "#fce7f3",
      card: "#241620",
      cardForeground: "#fce7f3",
      popover: "#241620",
      popoverForeground: "#fce7f3",
      border: "#4a2040",
      input: "#4a2040",
      ring: "#ec4899",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Arctic Frost",
    slug: "arctic-frost",
    description: "Clean and icy with cool grays and bright blues",
    colors: {
      background: "#f0f4f8",
      foreground: "#1a202c",
      primary: "#3b82f6",
      secondary: "#dbeafe",
      accent: "#60a5fa",
      muted: "#94a3b8",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#2563eb",
      string: "#059669",
      comment: "#94a3b8",
      function: "#3b82f6",
      variable: "#1a202c",
      type: "#d97706",
      number: "#dc2626",
      operator: "#6b7280",
      punctuation: "#94a3b8",
    },
    discord: {
      backgroundPrimary: "#f0f4f8",
      backgroundSecondary: "#e2e8f0",
      backgroundTertiary: "#cbd5e1",
      backgroundFloating: "#ffffff",
      textNormal: "#1a202c",
      textMuted: "#64748b",
      textLink: "#3b82f6",
      interactiveNormal: "#475569",
      interactiveHover: "#1e293b",
      interactiveActive: "#0f172a",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#3b82f6",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#1a202c",
      accentForeground: "#ffffff",
      mutedForeground: "#1a202c",
      card: "#ffffff",
      cardForeground: "#1a202c",
      popover: "#ffffff",
      popoverForeground: "#1a202c",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#3b82f6",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Warm Paper",
    slug: "warm-paper",
    description: "A cozy light theme that's easy on the eyes",
    colors: {
      background: "#faf8f5",
      foreground: "#2c2420",
      primary: "#b45309",
      secondary: "#fef3c7",
      accent: "#d97706",
      muted: "#a8a29e",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#92400e",
      string: "#065f46",
      comment: "#a8a29e",
      function: "#b45309",
      variable: "#2c2420",
      type: "#991b1b",
      number: "#7c3aed",
      operator: "#6b7280",
      punctuation: "#a8a29e",
    },
    discord: {
      backgroundPrimary: "#faf8f5",
      backgroundSecondary: "#f0ede5",
      backgroundTertiary: "#e5e0d4",
      backgroundFloating: "#ffffff",
      textNormal: "#2c2420",
      textMuted: "#78716c",
      textLink: "#b45309",
      interactiveNormal: "#44403c",
      interactiveHover: "#1c1917",
      interactiveActive: "#0c0a09",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#b45309",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#2c2420",
      accentForeground: "#ffffff",
      mutedForeground: "#2c2420",
      card: "#ffffff",
      cardForeground: "#2c2420",
      popover: "#ffffff",
      popoverForeground: "#2c2420",
      border: "#e5e0d4",
      input: "#e5e0d4",
      ring: "#b45309",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      radius: "0.375rem",
    },
  },
  {
    name: "Neon Cyberpunk",
    slug: "neon-cyberpunk",
    description: "High contrast neon colors on dark backgrounds",
    colors: {
      background: "#0a0a0a",
      foreground: "#00ff88",
      primary: "#ff0080",
      secondary: "#1a1a2e",
      accent: "#00ffff",
      muted: "#555577",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#ff0080",
      string: "#00ff88",
      comment: "#555577",
      function: "#00ffff",
      variable: "#f0f0f0",
      type: "#ffff00",
      number: "#ff8800",
      operator: "#ff0080",
      punctuation: "#555577",
    },
    discord: {
      backgroundPrimary: "#181820",
      backgroundSecondary: "#141420",
      backgroundTertiary: "#0a0a0a",
      backgroundFloating: "#050505",
      textNormal: "#00ff88",
      textMuted: "#555577",
      textLink: "#00ffff",
      interactiveNormal: "#00cc70",
      interactiveHover: "#00ff88",
      interactiveActive: "#ffffff",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#ff0080",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#00ff88",
      accentForeground: "#000000",
      mutedForeground: "#00ff88",
      card: "#141420",
      cardForeground: "#00ff88",
      popover: "#141420",
      popoverForeground: "#00ff88",
      border: "#2a2a3e",
      input: "#2a2a3e",
      ring: "#ff0080",
      destructive: "#ff0040",
      destructiveForeground: "#ffffff",
      radius: "0rem",
    },
  },
  {
    name: "Dracula Pro",
    slug: "dracula-pro",
    description: "Inspired by the popular Dracula color scheme",
    colors: {
      background: "#282a36",
      foreground: "#f8f8f2",
      primary: "#bd93f9",
      secondary: "#44475a",
      accent: "#ff79c6",
      muted: "#6272a4",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#ff79c6",
      string: "#f1fa8c",
      comment: "#6272a4",
      function: "#50fa7b",
      variable: "#f8f8f2",
      type: "#8be9fd",
      number: "#bd93f9",
      operator: "#ff79c6",
      punctuation: "#f8f8f2",
    },
    discord: {
      backgroundPrimary: "#36384a",
      backgroundSecondary: "#2f3142",
      backgroundTertiary: "#282a36",
      backgroundFloating: "#21232e",
      textNormal: "#f8f8f2",
      textMuted: "#6272a4",
      textLink: "#8be9fd",
      interactiveNormal: "#bbbec9",
      interactiveHover: "#f8f8f2",
      interactiveActive: "#ffffff",
      statusOnline: "#50fa7b",
      statusIdle: "#f1fa8c",
      statusDnd: "#ff5555",
      statusOffline: "#6272a4",
      brand: "#bd93f9",
    },
    tailwind: {
      primaryForeground: "#282a36",
      secondaryForeground: "#f8f8f2",
      accentForeground: "#282a36",
      mutedForeground: "#f8f8f2",
      card: "#2f3142",
      cardForeground: "#f8f8f2",
      popover: "#2f3142",
      popoverForeground: "#f8f8f2",
      border: "#44475a",
      input: "#44475a",
      ring: "#bd93f9",
      destructive: "#ff5555",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Solarized Dark",
    slug: "solarized-dark",
    description: "The classic Solarized color scheme for dark backgrounds",
    colors: {
      background: "#002b36",
      foreground: "#839496",
      primary: "#268bd2",
      secondary: "#073642",
      accent: "#2aa198",
      muted: "#586e75",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#859900",
      string: "#2aa198",
      comment: "#586e75",
      function: "#268bd2",
      variable: "#839496",
      type: "#b58900",
      number: "#d33682",
      operator: "#657b83",
      punctuation: "#657b83",
    },
    discord: {
      backgroundPrimary: "#0f3d4a",
      backgroundSecondary: "#073642",
      backgroundTertiary: "#002b36",
      backgroundFloating: "#001f29",
      textNormal: "#839496",
      textMuted: "#586e75",
      textLink: "#268bd2",
      interactiveNormal: "#657b83",
      interactiveHover: "#839496",
      interactiveActive: "#93a1a1",
      statusOnline: "#859900",
      statusIdle: "#b58900",
      statusDnd: "#dc322f",
      statusOffline: "#586e75",
      brand: "#268bd2",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#839496",
      accentForeground: "#002b36",
      mutedForeground: "#839496",
      card: "#073642",
      cardForeground: "#839496",
      popover: "#073642",
      popoverForeground: "#839496",
      border: "#0a4a5a",
      input: "#0a4a5a",
      ring: "#268bd2",
      destructive: "#dc322f",
      destructiveForeground: "#fdf6e3",
      radius: "0.5rem",
    },
  },
];

const EXTRA_THEMES = [
  {
    name: "Tokyo Night",
    slug: "tokyo-night",
    description: "Dark blues and purples inspired by Tokyo's nighttime cityscape",
    colors: {
      background: "#1a1b2e",
      foreground: "#c0caf5",
      primary: "#7aa2f7",
      secondary: "#24283b",
      accent: "#bb9af7",
      muted: "#565f89",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#bb9af7",
      string: "#9ece6a",
      comment: "#565f89",
      function: "#7aa2f7",
      variable: "#c0caf5",
      type: "#e0af68",
      number: "#ff9e64",
      operator: "#89ddff",
      punctuation: "#cfc9c2",
    },
    discord: {
      backgroundPrimary: "#22243a",
      backgroundSecondary: "#1e2035",
      backgroundTertiary: "#1a1b2e",
      backgroundFloating: "#131422",
      textNormal: "#c0caf5",
      textMuted: "#565f89",
      textLink: "#7aa2f7",
      interactiveNormal: "#9aa5ce",
      interactiveHover: "#c0caf5",
      interactiveActive: "#ffffff",
      statusOnline: "#9ece6a",
      statusIdle: "#e0af68",
      statusDnd: "#f7768e",
      statusOffline: "#565f89",
      brand: "#7aa2f7",
    },
    tailwind: {
      primaryForeground: "#1a1b2e",
      secondaryForeground: "#c0caf5",
      accentForeground: "#1a1b2e",
      mutedForeground: "#c0caf5",
      card: "#1e2035",
      cardForeground: "#c0caf5",
      popover: "#1e2035",
      popoverForeground: "#c0caf5",
      border: "#2a2f48",
      input: "#2a2f48",
      ring: "#7aa2f7",
      destructive: "#f7768e",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Gruvbox Dark",
    slug: "gruvbox-dark",
    description: "Retro groove colors with warm, earthy tones on dark background",
    colors: {
      background: "#282828",
      foreground: "#ebdbb2",
      primary: "#fabd2f",
      secondary: "#3c3836",
      accent: "#fe8019",
      muted: "#928374",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#fb4934",
      string: "#b8bb26",
      comment: "#928374",
      function: "#8ec07c",
      variable: "#ebdbb2",
      type: "#d3869b",
      number: "#d3869b",
      operator: "#fe8019",
      punctuation: "#ebdbb2",
    },
    discord: {
      backgroundPrimary: "#353535",
      backgroundSecondary: "#2e2e2e",
      backgroundTertiary: "#282828",
      backgroundFloating: "#1d1d1d",
      textNormal: "#ebdbb2",
      textMuted: "#928374",
      textLink: "#83a598",
      interactiveNormal: "#bdae93",
      interactiveHover: "#ebdbb2",
      interactiveActive: "#fbf1c7",
      statusOnline: "#b8bb26",
      statusIdle: "#fabd2f",
      statusDnd: "#fb4934",
      statusOffline: "#928374",
      brand: "#fabd2f",
    },
    tailwind: {
      primaryForeground: "#282828",
      secondaryForeground: "#ebdbb2",
      accentForeground: "#282828",
      mutedForeground: "#ebdbb2",
      card: "#2e2e2e",
      cardForeground: "#ebdbb2",
      popover: "#2e2e2e",
      popoverForeground: "#ebdbb2",
      border: "#504945",
      input: "#504945",
      ring: "#fabd2f",
      destructive: "#cc241d",
      destructiveForeground: "#fbf1c7",
      radius: "0.25rem",
    },
  },
  {
    name: "Catppuccin Mocha",
    slug: "catppuccin-mocha",
    description: "Pastel tones on a soft dark base for a cozy feel",
    colors: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      primary: "#cba6f7",
      secondary: "#313244",
      accent: "#f38ba8",
      muted: "#6c7086",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#cba6f7",
      string: "#a6e3a1",
      comment: "#6c7086",
      function: "#89b4fa",
      variable: "#cdd6f4",
      type: "#f9e2af",
      number: "#fab387",
      operator: "#89dceb",
      punctuation: "#cdd6f4",
    },
    discord: {
      backgroundPrimary: "#25253a",
      backgroundSecondary: "#232336",
      backgroundTertiary: "#1e1e2e",
      backgroundFloating: "#181825",
      textNormal: "#cdd6f4",
      textMuted: "#6c7086",
      textLink: "#89b4fa",
      interactiveNormal: "#a6adc8",
      interactiveHover: "#cdd6f4",
      interactiveActive: "#ffffff",
      statusOnline: "#a6e3a1",
      statusIdle: "#f9e2af",
      statusDnd: "#f38ba8",
      statusOffline: "#6c7086",
      brand: "#cba6f7",
    },
    tailwind: {
      primaryForeground: "#1e1e2e",
      secondaryForeground: "#cdd6f4",
      accentForeground: "#1e1e2e",
      mutedForeground: "#cdd6f4",
      card: "#232336",
      cardForeground: "#cdd6f4",
      popover: "#232336",
      popoverForeground: "#cdd6f4",
      border: "#45475a",
      input: "#45475a",
      ring: "#cba6f7",
      destructive: "#f38ba8",
      destructiveForeground: "#1e1e2e",
      radius: "0.5rem",
    },
  },
  {
    name: "Nord",
    slug: "nord",
    description: "An arctic, north-bluish color palette with calm, cool tones",
    colors: {
      background: "#2e3440",
      foreground: "#eceff4",
      primary: "#88c0d0",
      secondary: "#3b4252",
      accent: "#81a1c1",
      muted: "#4c566a",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#81a1c1",
      string: "#a3be8c",
      comment: "#4c566a",
      function: "#88c0d0",
      variable: "#eceff4",
      type: "#8fbcbb",
      number: "#b48ead",
      operator: "#81a1c1",
      punctuation: "#d8dee9",
    },
    discord: {
      backgroundPrimary: "#363e4e",
      backgroundSecondary: "#323a4a",
      backgroundTertiary: "#2e3440",
      backgroundFloating: "#272d3a",
      textNormal: "#eceff4",
      textMuted: "#4c566a",
      textLink: "#88c0d0",
      interactiveNormal: "#d8dee9",
      interactiveHover: "#eceff4",
      interactiveActive: "#ffffff",
      statusOnline: "#a3be8c",
      statusIdle: "#ebcb8b",
      statusDnd: "#bf616a",
      statusOffline: "#4c566a",
      brand: "#88c0d0",
    },
    tailwind: {
      primaryForeground: "#2e3440",
      secondaryForeground: "#eceff4",
      accentForeground: "#2e3440",
      mutedForeground: "#eceff4",
      card: "#323a4a",
      cardForeground: "#eceff4",
      popover: "#323a4a",
      popoverForeground: "#eceff4",
      border: "#434c5e",
      input: "#434c5e",
      ring: "#88c0d0",
      destructive: "#bf616a",
      destructiveForeground: "#eceff4",
      radius: "0.375rem",
    },
  },
  {
    name: "One Dark Pro",
    slug: "one-dark-pro",
    description: "The iconic dark theme from Atom, refined for elegant coding",
    colors: {
      background: "#282c34",
      foreground: "#abb2bf",
      primary: "#61afef",
      secondary: "#31353f",
      accent: "#e06c75",
      muted: "#5c6370",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#c678dd",
      string: "#98c379",
      comment: "#5c6370",
      function: "#61afef",
      variable: "#abb2bf",
      type: "#e5c07b",
      number: "#d19a66",
      operator: "#56b6c2",
      punctuation: "#abb2bf",
    },
    discord: {
      backgroundPrimary: "#30353f",
      backgroundSecondary: "#2e3238",
      backgroundTertiary: "#282c34",
      backgroundFloating: "#22262d",
      textNormal: "#abb2bf",
      textMuted: "#5c6370",
      textLink: "#61afef",
      interactiveNormal: "#828997",
      interactiveHover: "#abb2bf",
      interactiveActive: "#ffffff",
      statusOnline: "#98c379",
      statusIdle: "#e5c07b",
      statusDnd: "#e06c75",
      statusOffline: "#5c6370",
      brand: "#61afef",
    },
    tailwind: {
      primaryForeground: "#282c34",
      secondaryForeground: "#abb2bf",
      accentForeground: "#ffffff",
      mutedForeground: "#abb2bf",
      card: "#2e3238",
      cardForeground: "#abb2bf",
      popover: "#2e3238",
      popoverForeground: "#abb2bf",
      border: "#3e4450",
      input: "#3e4450",
      ring: "#61afef",
      destructive: "#e06c75",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Monokai",
    slug: "monokai",
    description: "The classic Monokai color scheme beloved by developers everywhere",
    colors: {
      background: "#272822",
      foreground: "#f8f8f2",
      primary: "#a6e22e",
      secondary: "#3e3d32",
      accent: "#f92672",
      muted: "#75715e",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#f92672",
      string: "#e6db74",
      comment: "#75715e",
      function: "#a6e22e",
      variable: "#f8f8f2",
      type: "#66d9e8",
      number: "#ae81ff",
      operator: "#f92672",
      punctuation: "#f8f8f2",
    },
    discord: {
      backgroundPrimary: "#32312a",
      backgroundSecondary: "#2e2d27",
      backgroundTertiary: "#272822",
      backgroundFloating: "#1f1e1a",
      textNormal: "#f8f8f2",
      textMuted: "#75715e",
      textLink: "#66d9e8",
      interactiveNormal: "#cfcfc2",
      interactiveHover: "#f8f8f2",
      interactiveActive: "#ffffff",
      statusOnline: "#a6e22e",
      statusIdle: "#e6db74",
      statusDnd: "#f92672",
      statusOffline: "#75715e",
      brand: "#a6e22e",
    },
    tailwind: {
      primaryForeground: "#272822",
      secondaryForeground: "#f8f8f2",
      accentForeground: "#272822",
      mutedForeground: "#f8f8f2",
      card: "#2e2d27",
      cardForeground: "#f8f8f2",
      popover: "#2e2d27",
      popoverForeground: "#f8f8f2",
      border: "#3e3d32",
      input: "#3e3d32",
      ring: "#a6e22e",
      destructive: "#f92672",
      destructiveForeground: "#ffffff",
      radius: "0.25rem",
    },
  },
  {
    name: "GitHub Dark",
    slug: "github-dark",
    description: "GitHub's official dark mode palette for a familiar developer experience",
    colors: {
      background: "#0d1117",
      foreground: "#e6edf3",
      primary: "#58a6ff",
      secondary: "#161b22",
      accent: "#3fb950",
      muted: "#8b949e",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#ff7b72",
      string: "#a5d6ff",
      comment: "#8b949e",
      function: "#d2a8ff",
      variable: "#e6edf3",
      type: "#79c0ff",
      number: "#79c0ff",
      operator: "#ff7b72",
      punctuation: "#e6edf3",
    },
    discord: {
      backgroundPrimary: "#161b22",
      backgroundSecondary: "#131920",
      backgroundTertiary: "#0d1117",
      backgroundFloating: "#090d12",
      textNormal: "#e6edf3",
      textMuted: "#8b949e",
      textLink: "#58a6ff",
      interactiveNormal: "#b1bac4",
      interactiveHover: "#e6edf3",
      interactiveActive: "#ffffff",
      statusOnline: "#3fb950",
      statusIdle: "#d29922",
      statusDnd: "#f85149",
      statusOffline: "#8b949e",
      brand: "#58a6ff",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#e6edf3",
      accentForeground: "#0d1117",
      mutedForeground: "#e6edf3",
      card: "#131920",
      cardForeground: "#e6edf3",
      popover: "#131920",
      popoverForeground: "#e6edf3",
      border: "#30363d",
      input: "#30363d",
      ring: "#58a6ff",
      destructive: "#f85149",
      destructiveForeground: "#ffffff",
      radius: "0.375rem",
    },
  },
  {
    name: "Everforest",
    slug: "everforest",
    description: "A green-based color scheme with warm, natural tones",
    colors: {
      background: "#2d353b",
      foreground: "#d3c6aa",
      primary: "#a7c080",
      secondary: "#3d484d",
      accent: "#e69875",
      muted: "#7a8478",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#e67e80",
      string: "#a7c080",
      comment: "#7a8478",
      function: "#7fbbb3",
      variable: "#d3c6aa",
      type: "#dbbc7f",
      number: "#d699b6",
      operator: "#e69875",
      punctuation: "#859289",
    },
    discord: {
      backgroundPrimary: "#3a4248",
      backgroundSecondary: "#343c42",
      backgroundTertiary: "#2d353b",
      backgroundFloating: "#252d32",
      textNormal: "#d3c6aa",
      textMuted: "#7a8478",
      textLink: "#7fbbb3",
      interactiveNormal: "#b4bec4",
      interactiveHover: "#d3c6aa",
      interactiveActive: "#ffffff",
      statusOnline: "#a7c080",
      statusIdle: "#dbbc7f",
      statusDnd: "#e67e80",
      statusOffline: "#7a8478",
      brand: "#a7c080",
    },
    tailwind: {
      primaryForeground: "#2d353b",
      secondaryForeground: "#d3c6aa",
      accentForeground: "#2d353b",
      mutedForeground: "#d3c6aa",
      card: "#343c42",
      cardForeground: "#d3c6aa",
      popover: "#343c42",
      popoverForeground: "#d3c6aa",
      border: "#4a5560",
      input: "#4a5560",
      ring: "#a7c080",
      destructive: "#e67e80",
      destructiveForeground: "#2d353b",
      radius: "0.375rem",
    },
  },
  {
    name: "Ayu Mirage",
    slug: "ayu-mirage",
    description: "Smooth dark theme with amber highlights and soothing mid-tones",
    colors: {
      background: "#1f2430",
      foreground: "#cbccc6",
      primary: "#ffcc66",
      secondary: "#2a2f3f",
      accent: "#f28779",
      muted: "#5c6773",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#ffa759",
      string: "#bae67e",
      comment: "#5c6773",
      function: "#5ccfe6",
      variable: "#cbccc6",
      type: "#ffd580",
      number: "#ffcc66",
      operator: "#f29e74",
      punctuation: "#cbccc6",
    },
    discord: {
      backgroundPrimary: "#272d3e",
      backgroundSecondary: "#232838",
      backgroundTertiary: "#1f2430",
      backgroundFloating: "#181d28",
      textNormal: "#cbccc6",
      textMuted: "#5c6773",
      textLink: "#5ccfe6",
      interactiveNormal: "#a2a8b2",
      interactiveHover: "#cbccc6",
      interactiveActive: "#ffffff",
      statusOnline: "#bae67e",
      statusIdle: "#ffd580",
      statusDnd: "#f28779",
      statusOffline: "#5c6773",
      brand: "#ffcc66",
    },
    tailwind: {
      primaryForeground: "#1f2430",
      secondaryForeground: "#cbccc6",
      accentForeground: "#1f2430",
      mutedForeground: "#cbccc6",
      card: "#232838",
      cardForeground: "#cbccc6",
      popover: "#232838",
      popoverForeground: "#cbccc6",
      border: "#35404e",
      input: "#35404e",
      ring: "#ffcc66",
      destructive: "#f28779",
      destructiveForeground: "#1f2430",
      radius: "0.5rem",
    },
  },
  {
    name: "Material Oceanic",
    slug: "material-oceanic",
    description: "Material Design meets deep ocean blues for a productive dark theme",
    colors: {
      background: "#0f111a",
      foreground: "#8f93a2",
      primary: "#89ddff",
      secondary: "#1a1c25",
      accent: "#c792ea",
      muted: "#464b5d",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#c792ea",
      string: "#c3e88d",
      comment: "#546e7a",
      function: "#82aaff",
      variable: "#eeffff",
      type: "#ffcb6b",
      number: "#f78c6c",
      operator: "#89ddff",
      punctuation: "#89ddff",
    },
    discord: {
      backgroundPrimary: "#1a1c25",
      backgroundSecondary: "#161820",
      backgroundTertiary: "#0f111a",
      backgroundFloating: "#0a0c13",
      textNormal: "#8f93a2",
      textMuted: "#464b5d",
      textLink: "#89ddff",
      interactiveNormal: "#717786",
      interactiveHover: "#8f93a2",
      interactiveActive: "#eeffff",
      statusOnline: "#c3e88d",
      statusIdle: "#ffcb6b",
      statusDnd: "#ff5370",
      statusOffline: "#464b5d",
      brand: "#89ddff",
    },
    tailwind: {
      primaryForeground: "#0f111a",
      secondaryForeground: "#8f93a2",
      accentForeground: "#0f111a",
      mutedForeground: "#8f93a2",
      card: "#161820",
      cardForeground: "#8f93a2",
      popover: "#161820",
      popoverForeground: "#8f93a2",
      border: "#2a2d3a",
      input: "#2a2d3a",
      ring: "#89ddff",
      destructive: "#ff5370",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Kanagawa",
    slug: "kanagawa",
    description: "Inspired by the famous woodblock print, blending ink blacks with samurai reds",
    colors: {
      background: "#1f1f28",
      foreground: "#dcd7ba",
      primary: "#7e9cd8",
      secondary: "#2a2a37",
      accent: "#e46876",
      muted: "#727169",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#957fb8",
      string: "#98bb6c",
      comment: "#727169",
      function: "#7e9cd8",
      variable: "#dcd7ba",
      type: "#7aa89f",
      number: "#d27e99",
      operator: "#c0a36e",
      punctuation: "#9cabca",
    },
    discord: {
      backgroundPrimary: "#272730",
      backgroundSecondary: "#232230",
      backgroundTertiary: "#1f1f28",
      backgroundFloating: "#191922",
      textNormal: "#dcd7ba",
      textMuted: "#727169",
      textLink: "#7e9cd8",
      interactiveNormal: "#b0a994",
      interactiveHover: "#dcd7ba",
      interactiveActive: "#ffffff",
      statusOnline: "#98bb6c",
      statusIdle: "#c0a36e",
      statusDnd: "#e46876",
      statusOffline: "#727169",
      brand: "#7e9cd8",
    },
    tailwind: {
      primaryForeground: "#1f1f28",
      secondaryForeground: "#dcd7ba",
      accentForeground: "#ffffff",
      mutedForeground: "#dcd7ba",
      card: "#232230",
      cardForeground: "#dcd7ba",
      popover: "#232230",
      popoverForeground: "#dcd7ba",
      border: "#363646",
      input: "#363646",
      ring: "#7e9cd8",
      destructive: "#e46876",
      destructiveForeground: "#ffffff",
      radius: "0.375rem",
    },
  },
  {
    name: "Rosé Pine",
    slug: "rose-pine",
    description: "Soho vibes with muted tones and a rosy glow",
    colors: {
      background: "#191724",
      foreground: "#e0def4",
      primary: "#c4a7e7",
      secondary: "#26233a",
      accent: "#ebbcba",
      muted: "#6e6a86",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#c4a7e7",
      string: "#9ccfd8",
      comment: "#6e6a86",
      function: "#ebbcba",
      variable: "#e0def4",
      type: "#f6c177",
      number: "#eb6f92",
      operator: "#3e8fb0",
      punctuation: "#908caa",
    },
    discord: {
      backgroundPrimary: "#252333",
      backgroundSecondary: "#22202e",
      backgroundTertiary: "#191724",
      backgroundFloating: "#131120",
      textNormal: "#e0def4",
      textMuted: "#6e6a86",
      textLink: "#9ccfd8",
      interactiveNormal: "#b4b2cc",
      interactiveHover: "#e0def4",
      interactiveActive: "#ffffff",
      statusOnline: "#9ccfd8",
      statusIdle: "#f6c177",
      statusDnd: "#eb6f92",
      statusOffline: "#6e6a86",
      brand: "#c4a7e7",
    },
    tailwind: {
      primaryForeground: "#191724",
      secondaryForeground: "#e0def4",
      accentForeground: "#191724",
      mutedForeground: "#e0def4",
      card: "#22202e",
      cardForeground: "#e0def4",
      popover: "#22202e",
      popoverForeground: "#e0def4",
      border: "#3a3755",
      input: "#3a3755",
      ring: "#c4a7e7",
      destructive: "#eb6f92",
      destructiveForeground: "#191724",
      radius: "0.5rem",
    },
  },
  {
    name: "Horizon",
    slug: "horizon",
    description: "Warm sunset hues meet dark backgrounds for a vivid, inspiring theme",
    colors: {
      background: "#1c1e26",
      foreground: "#d5d8da",
      primary: "#e95678",
      secondary: "#232530",
      accent: "#fab795",
      muted: "#6a6b83",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#e95678",
      string: "#29d398",
      comment: "#6a6b83",
      function: "#26bbd9",
      variable: "#d5d8da",
      type: "#eeeba5",
      number: "#fab795",
      operator: "#e95678",
      punctuation: "#6a6b83",
    },
    discord: {
      backgroundPrimary: "#262933",
      backgroundSecondary: "#21232e",
      backgroundTertiary: "#1c1e26",
      backgroundFloating: "#161820",
      textNormal: "#d5d8da",
      textMuted: "#6a6b83",
      textLink: "#26bbd9",
      interactiveNormal: "#b0b3ba",
      interactiveHover: "#d5d8da",
      interactiveActive: "#ffffff",
      statusOnline: "#29d398",
      statusIdle: "#fab795",
      statusDnd: "#e95678",
      statusOffline: "#6a6b83",
      brand: "#e95678",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#d5d8da",
      accentForeground: "#1c1e26",
      mutedForeground: "#d5d8da",
      card: "#21232e",
      cardForeground: "#d5d8da",
      popover: "#21232e",
      popoverForeground: "#d5d8da",
      border: "#333543",
      input: "#333543",
      ring: "#e95678",
      destructive: "#e95678",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Alabaster",
    slug: "alabaster",
    description: "Minimal light theme using a clean white base with soft contrast",
    colors: {
      background: "#f7f7f7",
      foreground: "#1a1a1a",
      primary: "#007acc",
      secondary: "#e8e8e8",
      accent: "#0e7490",
      muted: "#999999",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#af00db",
      string: "#008000",
      comment: "#999999",
      function: "#007acc",
      variable: "#1a1a1a",
      type: "#267f99",
      number: "#098658",
      operator: "#6b7280",
      punctuation: "#999999",
    },
    discord: {
      backgroundPrimary: "#f7f7f7",
      backgroundSecondary: "#eeeeee",
      backgroundTertiary: "#e5e5e5",
      backgroundFloating: "#ffffff",
      textNormal: "#1a1a1a",
      textMuted: "#777777",
      textLink: "#007acc",
      interactiveNormal: "#444444",
      interactiveHover: "#111111",
      interactiveActive: "#000000",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#007acc",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#1a1a1a",
      accentForeground: "#ffffff",
      mutedForeground: "#1a1a1a",
      card: "#ffffff",
      cardForeground: "#1a1a1a",
      popover: "#ffffff",
      popoverForeground: "#1a1a1a",
      border: "#e0e0e0",
      input: "#e0e0e0",
      ring: "#007acc",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Solarized Light",
    slug: "solarized-light",
    description: "The classic Solarized palette on a warm beige background",
    colors: {
      background: "#fdf6e3",
      foreground: "#657b83",
      primary: "#268bd2",
      secondary: "#eee8d5",
      accent: "#2aa198",
      muted: "#93a1a1",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#859900",
      string: "#2aa198",
      comment: "#93a1a1",
      function: "#268bd2",
      variable: "#657b83",
      type: "#b58900",
      number: "#d33682",
      operator: "#657b83",
      punctuation: "#93a1a1",
    },
    discord: {
      backgroundPrimary: "#fdf6e3",
      backgroundSecondary: "#eee8d5",
      backgroundTertiary: "#e3ddc8",
      backgroundFloating: "#ffffff",
      textNormal: "#657b83",
      textMuted: "#93a1a1",
      textLink: "#268bd2",
      interactiveNormal: "#586e75",
      interactiveHover: "#073642",
      interactiveActive: "#002b36",
      statusOnline: "#859900",
      statusIdle: "#b58900",
      statusDnd: "#dc322f",
      statusOffline: "#93a1a1",
      brand: "#268bd2",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#657b83",
      accentForeground: "#fdf6e3",
      mutedForeground: "#657b83",
      card: "#ffffff",
      cardForeground: "#657b83",
      popover: "#ffffff",
      popoverForeground: "#657b83",
      border: "#e0dac8",
      input: "#e0dac8",
      ring: "#268bd2",
      destructive: "#dc322f",
      destructiveForeground: "#fdf6e3",
      radius: "0.5rem",
    },
  },
  {
    name: "Flex Light",
    slug: "flex-light",
    description: "Airy white theme with vivid indigo accents for creative workflows",
    colors: {
      background: "#ffffff",
      foreground: "#1e293b",
      primary: "#6366f1",
      secondary: "#f1f5f9",
      accent: "#8b5cf6",
      muted: "#94a3b8",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#6366f1",
      string: "#16a34a",
      comment: "#94a3b8",
      function: "#8b5cf6",
      variable: "#1e293b",
      type: "#d97706",
      number: "#dc2626",
      operator: "#64748b",
      punctuation: "#94a3b8",
    },
    discord: {
      backgroundPrimary: "#f8fafc",
      backgroundSecondary: "#f1f5f9",
      backgroundTertiary: "#e2e8f0",
      backgroundFloating: "#ffffff",
      textNormal: "#1e293b",
      textMuted: "#64748b",
      textLink: "#6366f1",
      interactiveNormal: "#334155",
      interactiveHover: "#0f172a",
      interactiveActive: "#000000",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#6366f1",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#1e293b",
      accentForeground: "#ffffff",
      mutedForeground: "#1e293b",
      card: "#ffffff",
      cardForeground: "#1e293b",
      popover: "#ffffff",
      popoverForeground: "#1e293b",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#6366f1",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Panda Syntax",
    slug: "panda-syntax",
    description: "Superminimal dark theme with a dark teal base and coral accents",
    colors: {
      background: "#292a2b",
      foreground: "#e6e6e6",
      primary: "#19f9d8",
      secondary: "#363636",
      accent: "#ff75b5",
      muted: "#676b79",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#ff75b5",
      string: "#19f9d8",
      comment: "#676b79",
      function: "#6fc1ff",
      variable: "#e6e6e6",
      type: "#ffb86c",
      number: "#ff9ac1",
      operator: "#ff75b5",
      punctuation: "#676b79",
    },
    discord: {
      backgroundPrimary: "#363838",
      backgroundSecondary: "#32333a",
      backgroundTertiary: "#292a2b",
      backgroundFloating: "#222326",
      textNormal: "#e6e6e6",
      textMuted: "#676b79",
      textLink: "#19f9d8",
      interactiveNormal: "#b8b8b8",
      interactiveHover: "#e6e6e6",
      interactiveActive: "#ffffff",
      statusOnline: "#19f9d8",
      statusIdle: "#ffb86c",
      statusDnd: "#ff75b5",
      statusOffline: "#676b79",
      brand: "#19f9d8",
    },
    tailwind: {
      primaryForeground: "#292a2b",
      secondaryForeground: "#e6e6e6",
      accentForeground: "#292a2b",
      mutedForeground: "#e6e6e6",
      card: "#32333a",
      cardForeground: "#e6e6e6",
      popover: "#32333a",
      popoverForeground: "#e6e6e6",
      border: "#444648",
      input: "#444648",
      ring: "#19f9d8",
      destructive: "#ff75b5",
      destructiveForeground: "#292a2b",
      radius: "0.5rem",
    },
  },
  {
    name: "Cobalt2",
    slug: "cobalt2",
    description: "Bold royal blues with bright yellow accents — high energy coding",
    colors: {
      background: "#193549",
      foreground: "#ffffff",
      primary: "#ffc600",
      secondary: "#0d3a58",
      accent: "#ff628c",
      muted: "#0088ff",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#ff628c",
      string: "#3ad900",
      comment: "#0088ff",
      function: "#ffc600",
      variable: "#ffffff",
      type: "#9effff",
      number: "#ff628c",
      operator: "#ffc600",
      punctuation: "#ffffff",
    },
    discord: {
      backgroundPrimary: "#224260",
      backgroundSecondary: "#1e3a55",
      backgroundTertiary: "#193549",
      backgroundFloating: "#132a3a",
      textNormal: "#ffffff",
      textMuted: "#6ba3c4",
      textLink: "#9effff",
      interactiveNormal: "#cde4f4",
      interactiveHover: "#ffffff",
      interactiveActive: "#ffffff",
      statusOnline: "#3ad900",
      statusIdle: "#ffc600",
      statusDnd: "#ff628c",
      statusOffline: "#0088ff",
      brand: "#ffc600",
    },
    tailwind: {
      primaryForeground: "#193549",
      secondaryForeground: "#ffffff",
      accentForeground: "#193549",
      mutedForeground: "#ffffff",
      card: "#1e3a55",
      cardForeground: "#ffffff",
      popover: "#1e3a55",
      popoverForeground: "#ffffff",
      border: "#2a4f6a",
      input: "#2a4f6a",
      ring: "#ffc600",
      destructive: "#ff628c",
      destructiveForeground: "#193549",
      radius: "0.25rem",
    },
  },
  {
    name: "Night Owl",
    slug: "night-owl",
    description: "Refined syntax theme designed for those who prefer working late",
    colors: {
      background: "#011627",
      foreground: "#d6deeb",
      primary: "#82aaff",
      secondary: "#01121f",
      accent: "#c792ea",
      muted: "#637777",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#c792ea",
      string: "#ecc48d",
      comment: "#637777",
      function: "#82aaff",
      variable: "#d6deeb",
      type: "#addb67",
      number: "#f78c6c",
      operator: "#7fdbca",
      punctuation: "#d6deeb",
    },
    discord: {
      backgroundPrimary: "#0a1e2e",
      backgroundSecondary: "#061523",
      backgroundTertiary: "#011627",
      backgroundFloating: "#000f1a",
      textNormal: "#d6deeb",
      textMuted: "#637777",
      textLink: "#82aaff",
      interactiveNormal: "#a8b7c8",
      interactiveHover: "#d6deeb",
      interactiveActive: "#ffffff",
      statusOnline: "#addb67",
      statusIdle: "#ecc48d",
      statusDnd: "#ef5350",
      statusOffline: "#637777",
      brand: "#82aaff",
    },
    tailwind: {
      primaryForeground: "#011627",
      secondaryForeground: "#d6deeb",
      accentForeground: "#011627",
      mutedForeground: "#d6deeb",
      card: "#061523",
      cardForeground: "#d6deeb",
      popover: "#061523",
      popoverForeground: "#d6deeb",
      border: "#0d2137",
      input: "#0d2137",
      ring: "#82aaff",
      destructive: "#ef5350",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Zenburn",
    slug: "zenburn",
    description: "Low-contrast dark theme that is easy on the eyes during long sessions",
    colors: {
      background: "#3f3f3f",
      foreground: "#dcdccc",
      primary: "#8cd0d3",
      secondary: "#4a4a4a",
      accent: "#f0dfaf",
      muted: "#7f9f7f",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#e3ceab",
      string: "#cc9393",
      comment: "#7f9f7f",
      function: "#8cd0d3",
      variable: "#dcdccc",
      type: "#dfaf8f",
      number: "#8cd0d3",
      operator: "#f0efd0",
      punctuation: "#dcdccc",
    },
    discord: {
      backgroundPrimary: "#4a4a4a",
      backgroundSecondary: "#454545",
      backgroundTertiary: "#3f3f3f",
      backgroundFloating: "#383838",
      textNormal: "#dcdccc",
      textMuted: "#7f9f7f",
      textLink: "#8cd0d3",
      interactiveNormal: "#bcbcac",
      interactiveHover: "#dcdccc",
      interactiveActive: "#ffffff",
      statusOnline: "#7f9f7f",
      statusIdle: "#f0dfaf",
      statusDnd: "#cc9393",
      statusOffline: "#7f9f7f",
      brand: "#8cd0d3",
    },
    tailwind: {
      primaryForeground: "#3f3f3f",
      secondaryForeground: "#dcdccc",
      accentForeground: "#3f3f3f",
      mutedForeground: "#dcdccc",
      card: "#454545",
      cardForeground: "#dcdccc",
      popover: "#454545",
      popoverForeground: "#dcdccc",
      border: "#5a5a5a",
      input: "#5a5a5a",
      ring: "#8cd0d3",
      destructive: "#cc9393",
      destructiveForeground: "#3f3f3f",
      radius: "0.25rem",
    },
  },
  {
    name: "Palenight",
    slug: "palenight",
    description: "Elegant dark theme with blue-purple hues from the Material family",
    colors: {
      background: "#292d3e",
      foreground: "#a6accd",
      primary: "#82aaff",
      secondary: "#34364e",
      accent: "#c792ea",
      muted: "#676e95",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#c792ea",
      string: "#c3e88d",
      comment: "#676e95",
      function: "#82aaff",
      variable: "#a6accd",
      type: "#ffcb6b",
      number: "#f78c6c",
      operator: "#89ddff",
      punctuation: "#a6accd",
    },
    discord: {
      backgroundPrimary: "#353848",
      backgroundSecondary: "#313548",
      backgroundTertiary: "#292d3e",
      backgroundFloating: "#232736",
      textNormal: "#a6accd",
      textMuted: "#676e95",
      textLink: "#82aaff",
      interactiveNormal: "#8891b2",
      interactiveHover: "#a6accd",
      interactiveActive: "#ffffff",
      statusOnline: "#c3e88d",
      statusIdle: "#ffcb6b",
      statusDnd: "#ff5370",
      statusOffline: "#676e95",
      brand: "#82aaff",
    },
    tailwind: {
      primaryForeground: "#292d3e",
      secondaryForeground: "#a6accd",
      accentForeground: "#292d3e",
      mutedForeground: "#a6accd",
      card: "#313548",
      cardForeground: "#a6accd",
      popover: "#313548",
      popoverForeground: "#a6accd",
      border: "#404560",
      input: "#404560",
      ring: "#82aaff",
      destructive: "#ff5370",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Radical",
    slug: "radical",
    description: "Vivid dark theme with electric magenta and cyan bursting with energy",
    colors: {
      background: "#141221",
      foreground: "#f4f4f8",
      primary: "#ff857a",
      secondary: "#1e1b33",
      accent: "#25d7fd",
      muted: "#6b6b9a",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#ff857a",
      string: "#25d7fd",
      comment: "#6b6b9a",
      function: "#b084f8",
      variable: "#f4f4f8",
      type: "#ffd866",
      number: "#ff857a",
      operator: "#25d7fd",
      punctuation: "#6b6b9a",
    },
    discord: {
      backgroundPrimary: "#201e32",
      backgroundSecondary: "#1a1830",
      backgroundTertiary: "#141221",
      backgroundFloating: "#0e0c1a",
      textNormal: "#f4f4f8",
      textMuted: "#6b6b9a",
      textLink: "#25d7fd",
      interactiveNormal: "#c8c8d0",
      interactiveHover: "#f4f4f8",
      interactiveActive: "#ffffff",
      statusOnline: "#25d7fd",
      statusIdle: "#ffd866",
      statusDnd: "#ff857a",
      statusOffline: "#6b6b9a",
      brand: "#ff857a",
    },
    tailwind: {
      primaryForeground: "#141221",
      secondaryForeground: "#f4f4f8",
      accentForeground: "#141221",
      mutedForeground: "#f4f4f8",
      card: "#1a1830",
      cardForeground: "#f4f4f8",
      popover: "#1a1830",
      popoverForeground: "#f4f4f8",
      border: "#2e2a48",
      input: "#2e2a48",
      ring: "#ff857a",
      destructive: "#ff5370",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Flatland",
    slug: "flatland",
    description: "Flat, vivid colors on a deep dark background for a clean, modern look",
    colors: {
      background: "#1b2026",
      foreground: "#f0f0f0",
      primary: "#5af78e",
      secondary: "#252c35",
      accent: "#57c7ff",
      muted: "#4d5566",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#5af78e",
      string: "#f3f99d",
      comment: "#4d5566",
      function: "#57c7ff",
      variable: "#f0f0f0",
      type: "#9aedfe",
      number: "#ff6ac1",
      operator: "#abb2bf",
      punctuation: "#4d5566",
    },
    discord: {
      backgroundPrimary: "#272e36",
      backgroundSecondary: "#222830",
      backgroundTertiary: "#1b2026",
      backgroundFloating: "#151a20",
      textNormal: "#f0f0f0",
      textMuted: "#4d5566",
      textLink: "#57c7ff",
      interactiveNormal: "#c0c0c0",
      interactiveHover: "#f0f0f0",
      interactiveActive: "#ffffff",
      statusOnline: "#5af78e",
      statusIdle: "#f3f99d",
      statusDnd: "#ff5572",
      statusOffline: "#4d5566",
      brand: "#5af78e",
    },
    tailwind: {
      primaryForeground: "#1b2026",
      secondaryForeground: "#f0f0f0",
      accentForeground: "#1b2026",
      mutedForeground: "#f0f0f0",
      card: "#222830",
      cardForeground: "#f0f0f0",
      popover: "#222830",
      popoverForeground: "#f0f0f0",
      border: "#333d4a",
      input: "#333d4a",
      ring: "#5af78e",
      destructive: "#ff5572",
      destructiveForeground: "#ffffff",
      radius: "0.375rem",
    },
  },
  {
    name: "Sandcastle",
    slug: "sandcastle",
    description: "Warm sandy tones evoking a sun-soaked beach afternoon",
    colors: {
      background: "#f5f0e8",
      foreground: "#3d3226",
      primary: "#c0854a",
      secondary: "#ede6d9",
      accent: "#e07b39",
      muted: "#a89880",
    },
    fonts: { heading: "Georgia", body: "Georgia", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#c0854a",
      string: "#558b55",
      comment: "#a89880",
      function: "#a0683a",
      variable: "#3d3226",
      type: "#8b5e3c",
      number: "#b85c38",
      operator: "#6b5040",
      punctuation: "#a89880",
    },
    discord: {
      backgroundPrimary: "#f5f0e8",
      backgroundSecondary: "#ede6d9",
      backgroundTertiary: "#e3d8c8",
      backgroundFloating: "#ffffff",
      textNormal: "#3d3226",
      textMuted: "#8a7060",
      textLink: "#c0854a",
      interactiveNormal: "#5a4838",
      interactiveHover: "#2a1e12",
      interactiveActive: "#1a0e06",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#c0854a",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#3d3226",
      accentForeground: "#ffffff",
      mutedForeground: "#3d3226",
      card: "#ffffff",
      cardForeground: "#3d3226",
      popover: "#ffffff",
      popoverForeground: "#3d3226",
      border: "#ddd4c4",
      input: "#ddd4c4",
      ring: "#c0854a",
      destructive: "#c0392b",
      destructiveForeground: "#ffffff",
      radius: "0.375rem",
    },
  },
  {
    name: "Monochrome",
    slug: "monochrome",
    description: "Pure black and white design — zero distraction, maximum clarity",
    colors: {
      background: "#ffffff",
      foreground: "#000000",
      primary: "#000000",
      secondary: "#f0f0f0",
      accent: "#444444",
      muted: "#999999",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#000000",
      string: "#333333",
      comment: "#999999",
      function: "#111111",
      variable: "#000000",
      type: "#222222",
      number: "#555555",
      operator: "#444444",
      punctuation: "#999999",
    },
    discord: {
      backgroundPrimary: "#f5f5f5",
      backgroundSecondary: "#eeeeee",
      backgroundTertiary: "#e5e5e5",
      backgroundFloating: "#ffffff",
      textNormal: "#000000",
      textMuted: "#777777",
      textLink: "#000000",
      interactiveNormal: "#333333",
      interactiveHover: "#000000",
      interactiveActive: "#000000",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#000000",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#000000",
      accentForeground: "#ffffff",
      mutedForeground: "#000000",
      card: "#ffffff",
      cardForeground: "#000000",
      popover: "#ffffff",
      popoverForeground: "#000000",
      border: "#e0e0e0",
      input: "#e0e0e0",
      ring: "#000000",
      destructive: "#cc0000",
      destructiveForeground: "#ffffff",
      radius: "0rem",
    },
  },
  {
    name: "Ink Dark",
    slug: "ink-dark",
    description: "Absolute black background with off-white text — like ink on the void",
    colors: {
      background: "#000000",
      foreground: "#e8e8e8",
      primary: "#ffffff",
      secondary: "#111111",
      accent: "#cccccc",
      muted: "#555555",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#ffffff",
      string: "#aaaaaa",
      comment: "#555555",
      function: "#dddddd",
      variable: "#e8e8e8",
      type: "#bbbbbb",
      number: "#cccccc",
      operator: "#888888",
      punctuation: "#555555",
    },
    discord: {
      backgroundPrimary: "#1a1a1a",
      backgroundSecondary: "#111111",
      backgroundTertiary: "#000000",
      backgroundFloating: "#000000",
      textNormal: "#e8e8e8",
      textMuted: "#555555",
      textLink: "#cccccc",
      interactiveNormal: "#bbbbbb",
      interactiveHover: "#e8e8e8",
      interactiveActive: "#ffffff",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#555555",
      brand: "#ffffff",
    },
    tailwind: {
      primaryForeground: "#000000",
      secondaryForeground: "#e8e8e8",
      accentForeground: "#000000",
      mutedForeground: "#e8e8e8",
      card: "#111111",
      cardForeground: "#e8e8e8",
      popover: "#111111",
      popoverForeground: "#e8e8e8",
      border: "#222222",
      input: "#222222",
      ring: "#ffffff",
      destructive: "#cc0000",
      destructiveForeground: "#ffffff",
      radius: "0rem",
    },
  },
  {
    name: "Matcha Latte",
    slug: "matcha-latte",
    description: "Soft greens and creamy whites for a serene, café-inspired aesthetic",
    colors: {
      background: "#f4f7f0",
      foreground: "#2d3b2a",
      primary: "#5a8a50",
      secondary: "#e6eedf",
      accent: "#7aad6e",
      muted: "#8fa88c",
    },
    fonts: { heading: "Georgia", body: "Georgia", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#5a8a50",
      string: "#2e7d32",
      comment: "#8fa88c",
      function: "#4a7a40",
      variable: "#2d3b2a",
      type: "#6a8a2a",
      number: "#8b6914",
      operator: "#556b50",
      punctuation: "#8fa88c",
    },
    discord: {
      backgroundPrimary: "#f4f7f0",
      backgroundSecondary: "#eaefdf",
      backgroundTertiary: "#dde8d0",
      backgroundFloating: "#ffffff",
      textNormal: "#2d3b2a",
      textMuted: "#6a8068",
      textLink: "#5a8a50",
      interactiveNormal: "#3a5038",
      interactiveHover: "#1a2e18",
      interactiveActive: "#0a1e08",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#5a8a50",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#2d3b2a",
      accentForeground: "#2d3b2a",
      mutedForeground: "#2d3b2a",
      card: "#ffffff",
      cardForeground: "#2d3b2a",
      popover: "#ffffff",
      popoverForeground: "#2d3b2a",
      border: "#d5dece",
      input: "#d5dece",
      ring: "#5a8a50",
      destructive: "#c0392b",
      destructiveForeground: "#ffffff",
      radius: "0.375rem",
    },
  },
  {
    name: "Lavender Fields",
    slug: "lavender-fields",
    description: "Dreamy purples and soft whites reminiscent of Provençal lavender",
    colors: {
      background: "#f5f0ff",
      foreground: "#2d1f4e",
      primary: "#7c5cbf",
      secondary: "#ede5ff",
      accent: "#a480e0",
      muted: "#9e8fbf",
    },
    fonts: { heading: "Georgia", body: "Georgia", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#7c5cbf",
      string: "#3a7a3a",
      comment: "#9e8fbf",
      function: "#6a4aaf",
      variable: "#2d1f4e",
      type: "#b58900",
      number: "#d33682",
      operator: "#7a6a9a",
      punctuation: "#9e8fbf",
    },
    discord: {
      backgroundPrimary: "#f5f0ff",
      backgroundSecondary: "#ede5ff",
      backgroundTertiary: "#e3d8f5",
      backgroundFloating: "#ffffff",
      textNormal: "#2d1f4e",
      textMuted: "#7a6a9a",
      textLink: "#7c5cbf",
      interactiveNormal: "#4a3878",
      interactiveHover: "#2d1f4e",
      interactiveActive: "#1a0e35",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#7c5cbf",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#2d1f4e",
      accentForeground: "#ffffff",
      mutedForeground: "#2d1f4e",
      card: "#ffffff",
      cardForeground: "#2d1f4e",
      popover: "#ffffff",
      popoverForeground: "#2d1f4e",
      border: "#ddd5f5",
      input: "#ddd5f5",
      ring: "#7c5cbf",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
  {
    name: "Crimson Noir",
    slug: "crimson-noir",
    description: "Deep black and blood red — bold, dramatic, unapologetic",
    colors: {
      background: "#100a0a",
      foreground: "#f5e0e0",
      primary: "#cc1f1f",
      secondary: "#1e0f0f",
      accent: "#e84040",
      muted: "#6b4444",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#e84040",
      string: "#cc9999",
      comment: "#6b4444",
      function: "#cc1f1f",
      variable: "#f5e0e0",
      type: "#e89040",
      number: "#cc6060",
      operator: "#cc6666",
      punctuation: "#6b4444",
    },
    discord: {
      backgroundPrimary: "#1e1414",
      backgroundSecondary: "#181010",
      backgroundTertiary: "#100a0a",
      backgroundFloating: "#0a0505",
      textNormal: "#f5e0e0",
      textMuted: "#6b4444",
      textLink: "#e84040",
      interactiveNormal: "#cc9999",
      interactiveHover: "#f5e0e0",
      interactiveActive: "#ffffff",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#6b4444",
      brand: "#cc1f1f",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#f5e0e0",
      accentForeground: "#ffffff",
      mutedForeground: "#f5e0e0",
      card: "#181010",
      cardForeground: "#f5e0e0",
      popover: "#181010",
      popoverForeground: "#f5e0e0",
      border: "#3a1a1a",
      input: "#3a1a1a",
      ring: "#cc1f1f",
      destructive: "#e84040",
      destructiveForeground: "#ffffff",
      radius: "0.25rem",
    },
  },
  {
    name: "Slate Blue",
    slug: "slate-blue",
    description: "Calm corporate blues with a professional, trustworthy feel",
    colors: {
      background: "#f8fafc",
      foreground: "#1e293b",
      primary: "#3b82f6",
      secondary: "#e2e8f0",
      accent: "#2563eb",
      muted: "#94a3b8",
    },
    fonts: { heading: "Inter", body: "Inter", mono: "JetBrains Mono" },
    vscode: {
      keyword: "#2563eb",
      string: "#16a34a",
      comment: "#94a3b8",
      function: "#3b82f6",
      variable: "#1e293b",
      type: "#d97706",
      number: "#dc2626",
      operator: "#64748b",
      punctuation: "#94a3b8",
    },
    discord: {
      backgroundPrimary: "#f8fafc",
      backgroundSecondary: "#f1f5f9",
      backgroundTertiary: "#e2e8f0",
      backgroundFloating: "#ffffff",
      textNormal: "#1e293b",
      textMuted: "#64748b",
      textLink: "#3b82f6",
      interactiveNormal: "#334155",
      interactiveHover: "#0f172a",
      interactiveActive: "#000000",
      statusOnline: "#3ba55d",
      statusIdle: "#faa61a",
      statusDnd: "#ed4245",
      statusOffline: "#747f8d",
      brand: "#3b82f6",
    },
    tailwind: {
      primaryForeground: "#ffffff",
      secondaryForeground: "#1e293b",
      accentForeground: "#ffffff",
      mutedForeground: "#1e293b",
      card: "#ffffff",
      cardForeground: "#1e293b",
      popover: "#ffffff",
      popoverForeground: "#1e293b",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#3b82f6",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      radius: "0.5rem",
    },
  },
];

export const addAllSystemThemes = mutation({
  args: {},
  handler: async (ctx) => {
    let systemUser = await ctx.db
      .query("users")
      .withIndex("by_username", (q) => q.eq("username", "themedrops"))
      .first();

    if (!systemUser) {
      const systemUserId = await ctx.db.insert("users", {
        username: "themedrops",
        displayName: "themedrops",
        bio: "Official themedrops system account. These are the starter themes.",
        avatarUrl: undefined,
      });
      systemUser = await ctx.db.get(systemUserId);
    }

    if (!systemUser) throw new Error("Failed to find or create system user");

    let added = 0;
    for (const theme of [...SEED_THEMES, ...EXTRA_THEMES]) {
      const existing = await ctx.db
        .query("themes")
        .withIndex("by_slug", (q) => q.eq("slug", theme.slug))
        .first();
      if (existing) continue;

      await ctx.db.insert("themes", {
        ...theme,
        starCount: Math.floor(Math.random() * 80) + 5,
        forkCount: 0,
        authorId: systemUser._id,
        isPublic: true,
      });
      added++;
    }

    return `Added ${added} themes`;
  },
});

export const addSystemThemes = mutation({
  args: {},
  handler: async (ctx) => {
    // Find or create system user
    let systemUser = await ctx.db
      .query("users")
      .withIndex("by_username", (q) => q.eq("username", "themedrops"))
      .first();

    if (!systemUser) {
      const systemUserId = await ctx.db.insert("users", {
        username: "themedrops",
        displayName: "themedrops",
        bio: "Official themedrops system account. These are the starter themes.",
        avatarUrl: undefined,
      });
      systemUser = await ctx.db.get(systemUserId);
    }

    if (!systemUser) throw new Error("Failed to find or create system user");

    let added = 0;
    for (const theme of EXTRA_THEMES) {
      // Skip if slug already exists
      const existing = await ctx.db
        .query("themes")
        .withIndex("by_slug", (q) => q.eq("slug", theme.slug))
        .first();
      if (existing) continue;

      await ctx.db.insert("themes", {
        ...theme,
        starCount: Math.floor(Math.random() * 80) + 5,
        forkCount: 0,
        authorId: systemUser._id,
        isPublic: true,
      });
      added++;
    }

    return `Added ${added} themes`;
  },
});

export const seedData = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existingThemes = await ctx.db.query("themes").first();
    if (existingThemes) {
      return "Already seeded";
    }

    // Check if system user exists
    let systemUser = await ctx.db
      .query("users")
      .withIndex("by_username", (q) => q.eq("username", "themedrops"))
      .first();

    if (!systemUser) {
      const systemUserId = await ctx.db.insert("users", {
        username: "themedrops",
        displayName: "themedrops",
        bio: "Official themedrops system account. These are the starter themes.",
        avatarUrl: undefined,
      });
      systemUser = await ctx.db.get(systemUserId);
    }

    if (!systemUser) throw new Error("Failed to create system user");

    const tagCounts: Record<string, number> = {};
    for (const theme of SEED_THEMES) {
      const tags = THEME_TAGS[theme.slug];
      await ctx.db.insert("themes", {
        ...theme,
        tags,
        starCount: Math.floor(Math.random() * 50) + 5,
        forkCount: 0,
        authorId: systemUser._id,
        isPublic: true,
      });
      if (tags) {
        for (const tag of tags) {
          tagCounts[tag] = (tagCounts[tag] ?? 0) + 1;
        }
      }
    }

    // Insert tag counts
    for (const [name, count] of Object.entries(tagCounts)) {
      await ctx.db.insert("tags", { name, count });
    }

    return "Seeded " + SEED_THEMES.length + " themes";
  },
});

const THEME_TAGS: Record<string, string[]> = {
  "midnight-purple": ["dark", "vibrant", "bold"],
  "ocean-breeze": ["dark", "cool", "minimal"],
  "forest-canopy": ["dark", "warm", "monochrome"],
  "sunset-glow": ["dark", "warm", "vibrant"],
  "rose-gold": ["dark", "warm", "pastel"],
  "arctic-frost": ["dark", "cool", "minimal"],
  "warm-paper": ["light", "warm", "minimal"],
  "neon-cyberpunk": ["dark", "vibrant", "bold"],
  "dracula-pro": ["dark", "vibrant", "bold"],
  "solarized-dark": ["dark", "warm", "minimal"],
  "tokyo-night": ["dark", "cool", "vibrant"],
  "gruvbox-dark": ["dark", "warm", "retro"],
  "catppuccin-mocha": ["dark", "pastel", "warm"],
  "nord": ["dark", "cool", "minimal"],
  "one-dark-pro": ["dark", "cool", "minimal"],
  "monokai": ["dark", "vibrant", "bold"],
  "github-dark": ["dark", "minimal", "monochrome"],
  "everforest": ["dark", "warm", "pastel"],
  "ayu-mirage": ["dark", "warm", "minimal"],
  "material-oceanic": ["dark", "cool", "minimal"],
  "kanagawa": ["dark", "warm", "retro"],
  "rose-pine": ["dark", "pastel", "minimal"],
  "horizon": ["dark", "warm", "vibrant"],
  "alabaster": ["light", "warm", "minimal"],
  "solarized-light": ["light", "warm", "minimal"],
  "flex-light": ["light", "cool", "minimal"],
  "panda-syntax": ["dark", "vibrant", "bold"],
  "cobalt2": ["dark", "vibrant", "bold"],
  "night-owl": ["dark", "cool", "vibrant"],
  "zenburn": ["dark", "warm", "retro"],
  "palenight": ["dark", "pastel", "cool"],
  "radical": ["dark", "vibrant", "bold"],
  "flatland": ["dark", "minimal", "monochrome"],
  "sandcastle": ["light", "warm", "retro"],
  "monochrome": ["dark", "monochrome", "minimal"],
  "ink-dark": ["dark", "monochrome", "bold"],
  "matcha-latte": ["light", "pastel", "warm"],
  "lavender-fields": ["light", "pastel", "cool"],
  "crimson-noir": ["dark", "bold", "warm"],
  "slate-blue": ["dark", "cool", "minimal"],
};

export const backfillTags = mutation({
  args: {},
  handler: async (ctx) => {
    let updated = 0;
    const tagCounts: Record<string, number> = {};

    for (const [slug, tags] of Object.entries(THEME_TAGS)) {
      const theme = await ctx.db
        .query("themes")
        .withIndex("by_slug", (q) => q.eq("slug", slug))
        .first();

      if (!theme) continue;
      if (theme.tags && theme.tags.length > 0) continue;

      await ctx.db.patch(theme._id, { tags });
      updated++;

      if (theme.isPublic) {
        for (const tag of tags) {
          tagCounts[tag] = (tagCounts[tag] ?? 0) + 1;
        }
      }
    }

    // Upsert tag counts
    for (const [name, count] of Object.entries(tagCounts)) {
      const existing = await ctx.db
        .query("tags")
        .withIndex("by_name", (q) => q.eq("name", name))
        .first();
      if (existing) {
        await ctx.db.patch(existing._id, { count: existing.count + count });
      } else {
        await ctx.db.insert("tags", { name, count });
      }
    }

    return `Tagged ${updated} themes`;
  },
});

export const backfillPlatformThemes = mutation({
  args: {},
  handler: async (ctx) => {
    const allThemeData = [...SEED_THEMES, ...EXTRA_THEMES];
    let updated = 0;

    for (const themeData of allThemeData) {
      const existing = await ctx.db
        .query("themes")
        .withIndex("by_slug", (q) => q.eq("slug", themeData.slug))
        .first();

      if (!existing) continue;

      // Only patch if any platform field is missing
      if (!existing.vscode || !existing.discord || !existing.tailwind) {
        await ctx.db.patch(existing._id, {
          vscode: themeData.vscode,
          discord: themeData.discord,
          tailwind: themeData.tailwind,
        });
        updated++;
      }
    }

    return `Updated ${updated} themes with platform data`;
  },
});
