/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as ThemeSlugRouteImport } from './routes/theme/$slug'
import { Route as ThemeSlugEditRouteImport } from './routes/theme/$slug.edit'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeSlugRoute = ThemeSlugRouteImport.update({
  id: '/theme/$slug',
  path: '/theme/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeSlugEditRoute = ThemeSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ThemeSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/theme/$slug': typeof ThemeSlugRouteWithChildren
  '/user/$username': typeof UserUsernameRoute
  '/theme/$slug/edit': typeof ThemeSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/theme/$slug': typeof ThemeSlugRouteWithChildren
  '/user/$username': typeof UserUsernameRoute
  '/theme/$slug/edit': typeof ThemeSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/theme/$slug': typeof ThemeSlugRouteWithChildren
  '/user/$username': typeof UserUsernameRoute
  '/theme/$slug/edit': typeof ThemeSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/theme/$slug'
    | '/user/$username'
    | '/theme/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/theme/$slug' | '/user/$username' | '/theme/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/theme/$slug'
    | '/user/$username'
    | '/theme/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ThemeSlugRoute: typeof ThemeSlugRouteWithChildren
  UserUsernameRoute: typeof UserUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/$slug': {
      id: '/theme/$slug'
      path: '/theme/$slug'
      fullPath: '/theme/$slug'
      preLoaderRoute: typeof ThemeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/$slug/edit': {
      id: '/theme/$slug/edit'
      path: '/edit'
      fullPath: '/theme/$slug/edit'
      preLoaderRoute: typeof ThemeSlugEditRouteImport
      parentRoute: typeof ThemeSlugRoute
    }
  }
}

interface ThemeSlugRouteChildren {
  ThemeSlugEditRoute: typeof ThemeSlugEditRoute
}

const ThemeSlugRouteChildren: ThemeSlugRouteChildren = {
  ThemeSlugEditRoute: ThemeSlugEditRoute,
}

const ThemeSlugRouteWithChildren = ThemeSlugRoute._addFileChildren(
  ThemeSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ThemeSlugRoute: ThemeSlugRouteWithChildren,
  UserUsernameRoute: UserUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
